<?php

//SEE IF USER IS AUTHORIZED

//SEE IF USER NEEDS TO MAKE A GUESS

//PULL NY SPOT

//SHOW AVAIALBE GUESSES
//PULL DB QUERY OF CURRENT GUESSES
//SPIT OUT ALL NUMBERS WITH BOXES
//THOSE AVAILABLE CAN CLICK FOR GUESS
//THOSE TAKEN DISPLAY THOSE WHO GUESS



////////////////
//DB MODEL
//SPOT (unique)
//USERID (int)
//REDDIT NAME (varchar)
//TIMESTAMP (date)


?>
